export const COMPTEUR_INCRETEMENT_VALEUR = 'COMPTEUR_INCRETEMENT_VALEUR'
export const COMPTEUR_DECREMENT_VALEUR = 'COMPTEUR_DECREMENT_VALEUR'
export const COMPTEUR_RESET_VALEUR = 'COMPTEUR_RESET_VALEUR'
export const COMPTEUR_SET_VALEUR = 'COMPTEUR_SET_VALEUR'

export const AJOUT_TACHE = 'AJOUT_TACHE'
export const EFFECTUER_TACHE = 'EFFECTUER_TACHE'

export const SET_LOADING = 'SET_LOADING'
export const SET_CITATION = 'SET_CITATION'